name: Setup dependencies
description: Sets up required dependencies
runs:
  using: composite
  steps:
    - name: Install dependencies
      run: sudo apt install libffi-dev libncurses5-dev zlib1g zlib1g-dev libssl-dev libreadline-dev libbz2-dev libsqlite3-dev liblzma-dev
      shell: bash
    - name: asdf_install
      uses: asdf-vm/actions/install@v4
