blank_issues_enabled: false
contact_links:
  - name: Integration Support
    url: https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/discussions
    about: Please ask and answer questions here.
