from custom_components.octopus_energy.const import CONFIG_ACCOUNT_ID, CONFIG_KIND, CONFIG_KIND_ACCOUNT, CONFIG_MAIN_API_KEY, CONFIG_MAIN_CALORIFIC_VALUE, CONFIG_MAIN_ELECTRICITY_PRICE_CAP, CONFIG_MAIN_GAS_PRICE_CAP, CONFIG_MAIN_HOME_MINI_SETTINGS, CONFIG_MAIN_HOME_PRO_ADDRESS, CONFIG_MAIN_HOME_PRO_API_KEY, CONFIG_MAIN_HOME_PRO_SETTINGS, CONFIG_MAIN_INTELLIGENT_MANUAL_DISPATCHES, CONFIG_MAIN_INTELLIGENT_RATE_MODE, CONFIG_MAIN_INTELLIGENT_SETTINGS, CONFIG_MAIN_LIVE_ELECTRICITY_CONSUMPTION_REFRESH_IN_MINUTES, CONFIG_MAIN_LIVE_GAS_CONSUMPTION_REFRESH_IN_MINUTES, CONFIG_MAIN_OLD_ACCOUNT_ID, CONFIG_MAIN_OLD_API_KEY, CONFIG_MAIN_PRICE_CAP_SETTINGS, CONFIG_MAIN_SUPPORTS_LIVE_CONSUMPTION
import pytest
from custom_components.octopus_energy.config.main import async_migrate_main_config

data_v1 = {
  CONFIG_MAIN_OLD_API_KEY: "test-api-key",
  CONFIG_MAIN_OLD_ACCOUNT_ID: "A-123",
  "live_consumption_refresh_in_minutes": 30
}

data_v2 = {
  CONFIG_MAIN_OLD_API_KEY: "test-api-key",
  CONFIG_MAIN_OLD_ACCOUNT_ID: "A-123",
  CONFIG_MAIN_LIVE_ELECTRICITY_CONSUMPTION_REFRESH_IN_MINUTES: 30,
  CONFIG_MAIN_LIVE_GAS_CONSUMPTION_REFRESH_IN_MINUTES: 15,
}

data_v4 = {
  CONFIG_MAIN_OLD_API_KEY: "test-api-key",
  CONFIG_MAIN_OLD_ACCOUNT_ID: "A-123",
  CONFIG_MAIN_LIVE_ELECTRICITY_CONSUMPTION_REFRESH_IN_MINUTES: 30,
  CONFIG_MAIN_LIVE_GAS_CONSUMPTION_REFRESH_IN_MINUTES: 15,
  CONFIG_MAIN_HOME_PRO_ADDRESS: "http://10.1.1.1:8000",
}

data_v5 = {
  CONFIG_KIND: CONFIG_KIND_ACCOUNT, 
  CONFIG_MAIN_API_KEY: "test-api-key",
  CONFIG_ACCOUNT_ID: "A-123",
  CONFIG_MAIN_SUPPORTS_LIVE_CONSUMPTION: True,
  CONFIG_MAIN_LIVE_ELECTRICITY_CONSUMPTION_REFRESH_IN_MINUTES: 30,
  CONFIG_MAIN_LIVE_GAS_CONSUMPTION_REFRESH_IN_MINUTES: 15,
  CONFIG_MAIN_CALORIFIC_VALUE: 40,
  CONFIG_MAIN_ELECTRICITY_PRICE_CAP: 38.5,
  CONFIG_MAIN_GAS_PRICE_CAP: 10.5,
  CONFIG_MAIN_HOME_PRO_ADDRESS: "http://10.1.1.1",
  CONFIG_MAIN_HOME_PRO_API_KEY: "supersecret",
  CONFIG_MAIN_INTELLIGENT_MANUAL_DISPATCHES: True,
  CONFIG_MAIN_INTELLIGENT_RATE_MODE: "intelligent_mode"
}

data_v5_no_intelligent_settings = {
  CONFIG_KIND: CONFIG_KIND_ACCOUNT, 
  CONFIG_MAIN_API_KEY: "test-api-key",
  CONFIG_ACCOUNT_ID: "A-123",
  CONFIG_MAIN_SUPPORTS_LIVE_CONSUMPTION: True,
  CONFIG_MAIN_LIVE_ELECTRICITY_CONSUMPTION_REFRESH_IN_MINUTES: 30,
  CONFIG_MAIN_LIVE_GAS_CONSUMPTION_REFRESH_IN_MINUTES: 15,
  CONFIG_MAIN_CALORIFIC_VALUE: 40,
  CONFIG_MAIN_ELECTRICITY_PRICE_CAP: 38.5,
  CONFIG_MAIN_GAS_PRICE_CAP: 10.5,
  CONFIG_MAIN_HOME_PRO_ADDRESS: "http://10.1.1.1",
  CONFIG_MAIN_HOME_PRO_API_KEY: "supersecret",
}

data_v5_no_home_pro_settings = {
  CONFIG_KIND: CONFIG_KIND_ACCOUNT, 
  CONFIG_MAIN_API_KEY: "test-api-key",
  CONFIG_ACCOUNT_ID: "A-123",
  CONFIG_MAIN_SUPPORTS_LIVE_CONSUMPTION: True,
  CONFIG_MAIN_LIVE_ELECTRICITY_CONSUMPTION_REFRESH_IN_MINUTES: 30,
  CONFIG_MAIN_LIVE_GAS_CONSUMPTION_REFRESH_IN_MINUTES: 15,
  CONFIG_MAIN_CALORIFIC_VALUE: 40,
  CONFIG_MAIN_ELECTRICITY_PRICE_CAP: 38.5,
  CONFIG_MAIN_GAS_PRICE_CAP: 10.5,
}

data_v5_no_price_cap_settings = {
  CONFIG_KIND: CONFIG_KIND_ACCOUNT, 
  CONFIG_MAIN_API_KEY: "test-api-key",
  CONFIG_ACCOUNT_ID: "A-123",
  CONFIG_MAIN_SUPPORTS_LIVE_CONSUMPTION: True,
  CONFIG_MAIN_LIVE_ELECTRICITY_CONSUMPTION_REFRESH_IN_MINUTES: 30,
  CONFIG_MAIN_LIVE_GAS_CONSUMPTION_REFRESH_IN_MINUTES: 15,
  CONFIG_MAIN_CALORIFIC_VALUE: 40,
  CONFIG_MAIN_HOME_PRO_ADDRESS: "http://10.1.1.1",
  CONFIG_MAIN_HOME_PRO_API_KEY: "supersecret",
}

data_v5_no_mini_settings = {
  CONFIG_KIND: CONFIG_KIND_ACCOUNT, 
  CONFIG_MAIN_API_KEY: "test-api-key",
  CONFIG_ACCOUNT_ID: "A-123",
  CONFIG_MAIN_CALORIFIC_VALUE: 40,
  CONFIG_MAIN_ELECTRICITY_PRICE_CAP: 38.5,
  CONFIG_MAIN_GAS_PRICE_CAP: 10.5,
  CONFIG_MAIN_HOME_PRO_ADDRESS: "http://10.1.1.1",
  CONFIG_MAIN_HOME_PRO_API_KEY: "supersecret",
}

data_v6 = {
  CONFIG_KIND: CONFIG_KIND_ACCOUNT, 
  CONFIG_MAIN_API_KEY: "test-api-key",
  CONFIG_ACCOUNT_ID: "A-123",
  CONFIG_MAIN_HOME_MINI_SETTINGS: {
    CONFIG_MAIN_SUPPORTS_LIVE_CONSUMPTION: True,
    CONFIG_MAIN_LIVE_ELECTRICITY_CONSUMPTION_REFRESH_IN_MINUTES: 30,
    CONFIG_MAIN_LIVE_GAS_CONSUMPTION_REFRESH_IN_MINUTES: 15,
  },
  CONFIG_MAIN_CALORIFIC_VALUE: 40,
  CONFIG_MAIN_PRICE_CAP_SETTINGS: {
    CONFIG_MAIN_ELECTRICITY_PRICE_CAP: 38.5,
    CONFIG_MAIN_GAS_PRICE_CAP: 10.5,
  },
  CONFIG_MAIN_HOME_PRO_SETTINGS: {
    CONFIG_MAIN_HOME_PRO_ADDRESS: "http://10.1.1.1",
    CONFIG_MAIN_HOME_PRO_API_KEY: "supersecret",
  },
  CONFIG_MAIN_INTELLIGENT_SETTINGS: {
    CONFIG_MAIN_INTELLIGENT_MANUAL_DISPATCHES: True,
    CONFIG_MAIN_INTELLIGENT_RATE_MODE: "intelligent_mode"
  }
}

expected_data_v1 = {
  CONFIG_KIND: CONFIG_KIND_ACCOUNT,
  CONFIG_MAIN_API_KEY: "test-api-key",
  CONFIG_ACCOUNT_ID: "A-123",
  CONFIG_MAIN_HOME_MINI_SETTINGS: {
    CONFIG_MAIN_LIVE_ELECTRICITY_CONSUMPTION_REFRESH_IN_MINUTES: 30,
    CONFIG_MAIN_LIVE_GAS_CONSUMPTION_REFRESH_IN_MINUTES: 30,
  },
  "live_consumption_refresh_in_minutes": 30
}

expected_data_v2 = {
  CONFIG_KIND: CONFIG_KIND_ACCOUNT,
  CONFIG_MAIN_API_KEY: "test-api-key",
  CONFIG_ACCOUNT_ID: "A-123",
  CONFIG_MAIN_HOME_MINI_SETTINGS: {
    CONFIG_MAIN_LIVE_ELECTRICITY_CONSUMPTION_REFRESH_IN_MINUTES: 30,
    CONFIG_MAIN_LIVE_GAS_CONSUMPTION_REFRESH_IN_MINUTES: 15,
  }
}

expected_data_v4 = {
  CONFIG_MAIN_OLD_API_KEY: "test-api-key",
  CONFIG_MAIN_OLD_ACCOUNT_ID: "A-123",
  CONFIG_MAIN_HOME_MINI_SETTINGS: {
    CONFIG_MAIN_LIVE_ELECTRICITY_CONSUMPTION_REFRESH_IN_MINUTES: 30,
    CONFIG_MAIN_LIVE_GAS_CONSUMPTION_REFRESH_IN_MINUTES: 15,
  },
  CONFIG_MAIN_HOME_PRO_SETTINGS: {
    CONFIG_MAIN_HOME_PRO_ADDRESS: "http://10.1.1.1",
  }
}

expected_data_v5 = {
  CONFIG_KIND: CONFIG_KIND_ACCOUNT, 
  CONFIG_MAIN_API_KEY: "test-api-key",
  CONFIG_ACCOUNT_ID: "A-123",
  CONFIG_MAIN_HOME_MINI_SETTINGS: {
    CONFIG_MAIN_SUPPORTS_LIVE_CONSUMPTION: True,
    CONFIG_MAIN_LIVE_ELECTRICITY_CONSUMPTION_REFRESH_IN_MINUTES: 30,
    CONFIG_MAIN_LIVE_GAS_CONSUMPTION_REFRESH_IN_MINUTES: 15,
  },
  CONFIG_MAIN_CALORIFIC_VALUE: 40,
  CONFIG_MAIN_PRICE_CAP_SETTINGS: {
    CONFIG_MAIN_ELECTRICITY_PRICE_CAP: 38.5,
    CONFIG_MAIN_GAS_PRICE_CAP: 10.5,
  },
  CONFIG_MAIN_HOME_PRO_SETTINGS: {
    CONFIG_MAIN_HOME_PRO_API_KEY: "supersecret",
    CONFIG_MAIN_HOME_PRO_ADDRESS: "http://10.1.1.1"
  },
  CONFIG_MAIN_INTELLIGENT_SETTINGS: {
    CONFIG_MAIN_INTELLIGENT_MANUAL_DISPATCHES: True,
    CONFIG_MAIN_INTELLIGENT_RATE_MODE: "intelligent_mode"
  }
}

expected_data_v5_no_intelligent_settings = {
  CONFIG_KIND: CONFIG_KIND_ACCOUNT, 
  CONFIG_MAIN_API_KEY: "test-api-key",
  CONFIG_ACCOUNT_ID: "A-123",
  CONFIG_MAIN_HOME_MINI_SETTINGS: {
    CONFIG_MAIN_SUPPORTS_LIVE_CONSUMPTION: True,
    CONFIG_MAIN_LIVE_ELECTRICITY_CONSUMPTION_REFRESH_IN_MINUTES: 30,
    CONFIG_MAIN_LIVE_GAS_CONSUMPTION_REFRESH_IN_MINUTES: 15,
  },
  CONFIG_MAIN_CALORIFIC_VALUE: 40,
  CONFIG_MAIN_PRICE_CAP_SETTINGS: {
    CONFIG_MAIN_ELECTRICITY_PRICE_CAP: 38.5,
    CONFIG_MAIN_GAS_PRICE_CAP: 10.5,
  },
  CONFIG_MAIN_HOME_PRO_SETTINGS: {
    CONFIG_MAIN_HOME_PRO_API_KEY: "supersecret",
    CONFIG_MAIN_HOME_PRO_ADDRESS: "http://10.1.1.1"
  }
}

expected_data_v5_no_home_pro_settings = {
  CONFIG_KIND: CONFIG_KIND_ACCOUNT, 
  CONFIG_MAIN_API_KEY: "test-api-key",
  CONFIG_ACCOUNT_ID: "A-123",
  CONFIG_MAIN_HOME_MINI_SETTINGS: {
    CONFIG_MAIN_SUPPORTS_LIVE_CONSUMPTION: True,
    CONFIG_MAIN_LIVE_ELECTRICITY_CONSUMPTION_REFRESH_IN_MINUTES: 30,
    CONFIG_MAIN_LIVE_GAS_CONSUMPTION_REFRESH_IN_MINUTES: 15,
  },
  CONFIG_MAIN_CALORIFIC_VALUE: 40,
  CONFIG_MAIN_PRICE_CAP_SETTINGS: {
    CONFIG_MAIN_ELECTRICITY_PRICE_CAP: 38.5,
    CONFIG_MAIN_GAS_PRICE_CAP: 10.5,
  }
}

expected_data_v5_no_price_cap_settings = {
  CONFIG_KIND: CONFIG_KIND_ACCOUNT, 
  CONFIG_MAIN_API_KEY: "test-api-key",
  CONFIG_ACCOUNT_ID: "A-123",
  CONFIG_MAIN_HOME_MINI_SETTINGS: {
    CONFIG_MAIN_SUPPORTS_LIVE_CONSUMPTION: True,
    CONFIG_MAIN_LIVE_ELECTRICITY_CONSUMPTION_REFRESH_IN_MINUTES: 30,
    CONFIG_MAIN_LIVE_GAS_CONSUMPTION_REFRESH_IN_MINUTES: 15,
  },
  CONFIG_MAIN_CALORIFIC_VALUE: 40,
  CONFIG_MAIN_HOME_PRO_SETTINGS: {
    CONFIG_MAIN_HOME_PRO_API_KEY: "supersecret",
    CONFIG_MAIN_HOME_PRO_ADDRESS: "http://10.1.1.1"
  }
}

expected_data_v5_no_mini_settings = {
  CONFIG_KIND: CONFIG_KIND_ACCOUNT, 
  CONFIG_MAIN_API_KEY: "test-api-key",
  CONFIG_ACCOUNT_ID: "A-123",
  CONFIG_MAIN_CALORIFIC_VALUE: 40,
  CONFIG_MAIN_PRICE_CAP_SETTINGS: {
    CONFIG_MAIN_ELECTRICITY_PRICE_CAP: 38.5,
    CONFIG_MAIN_GAS_PRICE_CAP: 10.5,
  },
  CONFIG_MAIN_HOME_PRO_SETTINGS: {
    CONFIG_MAIN_HOME_PRO_API_KEY: "supersecret",
    CONFIG_MAIN_HOME_PRO_ADDRESS: "http://10.1.1.1"
  }
}

expected_data_v6_valid = {
  CONFIG_KIND: CONFIG_KIND_ACCOUNT, 
  CONFIG_MAIN_API_KEY: "test-api-key",
  CONFIG_ACCOUNT_ID: "A-123",
  CONFIG_MAIN_HOME_MINI_SETTINGS: {
    CONFIG_MAIN_SUPPORTS_LIVE_CONSUMPTION: True,
    CONFIG_MAIN_LIVE_ELECTRICITY_CONSUMPTION_REFRESH_IN_MINUTES: 30,
    CONFIG_MAIN_LIVE_GAS_CONSUMPTION_REFRESH_IN_MINUTES: 15,
  },
  CONFIG_MAIN_CALORIFIC_VALUE: 40,
  CONFIG_MAIN_PRICE_CAP_SETTINGS: {
    CONFIG_MAIN_ELECTRICITY_PRICE_CAP: 38.5,
    CONFIG_MAIN_GAS_PRICE_CAP: 10.5,
  },
  CONFIG_MAIN_HOME_PRO_SETTINGS: {
    CONFIG_MAIN_HOME_PRO_API_KEY: "supersecret",
    CONFIG_MAIN_HOME_PRO_ADDRESS: "http://10.1.1.1"
  },
  CONFIG_MAIN_INTELLIGENT_SETTINGS: {
    CONFIG_MAIN_INTELLIGENT_MANUAL_DISPATCHES: True,
    CONFIG_MAIN_INTELLIGENT_RATE_MODE: "intelligent_mode"
  }
}

expected_data_v6_invalid = {
  CONFIG_KIND: CONFIG_KIND_ACCOUNT, 
  CONFIG_MAIN_API_KEY: "test-api-key",
  CONFIG_ACCOUNT_ID: "A-123",
  CONFIG_MAIN_HOME_MINI_SETTINGS: {
    CONFIG_MAIN_SUPPORTS_LIVE_CONSUMPTION: True,
    CONFIG_MAIN_LIVE_ELECTRICITY_CONSUMPTION_REFRESH_IN_MINUTES: 30,
    CONFIG_MAIN_LIVE_GAS_CONSUMPTION_REFRESH_IN_MINUTES: 15,
  },
  CONFIG_MAIN_CALORIFIC_VALUE: 40,
  CONFIG_MAIN_PRICE_CAP_SETTINGS: {
    CONFIG_MAIN_ELECTRICITY_PRICE_CAP: 38.5,
    CONFIG_MAIN_GAS_PRICE_CAP: 10.5,
  },
  CONFIG_MAIN_INTELLIGENT_SETTINGS: {
    CONFIG_MAIN_INTELLIGENT_MANUAL_DISPATCHES: True,
    CONFIG_MAIN_INTELLIGENT_RATE_MODE: "intelligent_mode"
  }
}

@pytest.mark.asyncio
@pytest.mark.parametrize("version,data,expected_data",[
  (1, data_v1, expected_data_v1),
  (2, data_v2, expected_data_v2),
  (4, data_v4, expected_data_v4),
  (5, data_v5, expected_data_v5),
  (5, data_v5_no_intelligent_settings, expected_data_v5_no_intelligent_settings),
  (5, data_v5_no_mini_settings, expected_data_v5_no_mini_settings),
  (5, data_v5_no_price_cap_settings, expected_data_v5_no_price_cap_settings),
  (5, data_v5_no_home_pro_settings, expected_data_v5_no_home_pro_settings),
  (6, data_v6, expected_data_v6_valid),
  (6, {
    **data_v6, 
    CONFIG_MAIN_HOME_PRO_SETTINGS: {
      CONFIG_MAIN_HOME_PRO_ADDRESS: "None"
    }
  }, expected_data_v6_invalid),
  (6, {
    **data_v6, 
    CONFIG_MAIN_HOME_PRO_SETTINGS: {
      CONFIG_MAIN_HOME_PRO_ADDRESS: None
    }
  }, expected_data_v6_invalid),
  (6, {
    **data_v6, 
    CONFIG_MAIN_HOME_PRO_SETTINGS: {
      CONFIG_MAIN_HOME_PRO_ADDRESS: "10.1.1.1"
    }
  }, expected_data_v6_invalid),
  (6, {
    **data_v6, 
    CONFIG_MAIN_HOME_PRO_SETTINGS: {
      CONFIG_MAIN_HOME_PRO_ADDRESS: "http://10.1.1.1:3000"
    }
  }, expected_data_v6_invalid),
])
async def test_when_data_is_provided_then_migrated_correctly(version, data, expected_data):
  # Act
  updated_data = await async_migrate_main_config(version, data)

  # Assert
  assert updated_data == expected_data