DOMAIN = "octopus_energy"

CONFIG_API_KEY = "API_KEY"
CONFIG_TARIFF = "TARIFF"
CONFIG_TARIFF_CODE = "TARIFF_CODE"
CONFIG_ELEC_MPAN = "ELEC_MPAN"
CONFIG_ELEC_SN = "ELEC_SN"
CONFIG_GAS_MPRN = "GAS_MPRN"
CONFIG_GAS_SN = "GAS_SN"