name: Check for API deprecations
on:
  workflow_dispatch:
  schedule:
    # run once a week to check for deprecations
    - cron: '0 1 * * 0'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  check:
    if: ${{ github.event_name != 'schedule' || github.repository_owner == 'BottlecapDave' }}
    name: Check for deprecations
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Setup
        uses: ./.github/actions/setup
      - name: Install dependencies
        run: npm ci
      - name: Run checks
        run: |
          npm run check-graphql-deprecations
