blueprint:
  name: Octopus Energy - Join Saving Session (Custom Actions)
  description: Automatically joins saving sessions when they become available
  domain: automation
  author: BottlecapDave
  input:
    saving_session_event_entity:
      name: Saving session events
      description: The saving session event entity to join (e.g. event.octopus_energy_{{ACCOUNT_ID}}_octoplus_saving_session_events)
      selector:
        entity:
          filter:
          - domain:
            - event
            integration: octopus_energy
          multiple: false
    actions:
      name: Actions
      description: Notifications or similar to be run. {{message}} is an example message
      selector:
        action: {}
mode: single
variables:
  saving_session_event_entity: !input saving_session_event_entity
  message: >
    {% if state_attr(saving_session_event_entity, 'available_events') != None and state_attr(saving_session_event_entity, 'available_events') | length > 0 %}
      {% set event = state_attr(saving_session_event_entity, 'available_events')[0] %}
      {% set event_start = event['start'] %}
      Joined a new Octopus Energy saving session. It starts at {{ event_start.strftime('%H:%M') }} on {{ event_start.day }}/{{ event_start.month }} for {{ event.duration_in_minutes | int }} minutes.
    {% endif %}
trigger:
- platform: state
  entity_id: !input saving_session_event_entity
condition:
- condition: template
  value_template: "{{ state_attr(saving_session_event_entity, 'available_events') != None and state_attr(saving_session_event_entity, 'available_events') | length > 0 }}"
action:
- service: octopus_energy.join_octoplus_saving_session_event
  data:
    event_code: "{{ state_attr(saving_session_event_entity, 'available_events')[0]['code'] }}"
  target:
    entity_id: !input saving_session_event_entity
- choose: []
  default: !input actions
      
